name: 02-workflow-event

on:
  pull_request:
  workflow_dispatch:
  

jobs:
    echo:
        runs-on: ubuntu-latest
        steps:
           - name: Show the trigger
             run: echo "I have been exec by ${{ github.event_name }} event."
